'''
Created on Jan 26, 2016
CONFIG FILE THAT CONTAINS BASIC CONFIG INFO
@author: Ruchi.U
'''

DIRECTORY_TO_BE_MONITORED = 'G:\\UPLOAD_DIR';
ENCRYPTED_FILE_PATH = 'G:\\ENCRYPTED_FILES\\'
DOWNLOADED_FILES = 'G:\\DOWNLOADED_FILES\\'